### ISSUE TITLE
As an instructor, I want to be able to push a button to execute the group forming process so that I can retrieve the groups.

### ISSUE THREAD

**Issue by Brunswick-Khorasan** [snowminc/Groupformer#11]
This is the primary purpose of the tool. To easily form groups with both the instructor’s and student’s preferences.

**Comment by Brunswick-Khorasan** [comment]
Additional description from SRS:

The instructor should be able to press a button which causes the algorithm to generate some optimal groupings of participants, which is then output onto the screen.

**Comment by KristianMischke** [comment]
mockup:
![image](https://user-images.githubusercontent.com/4390379/108923972-c82a5c00-7607-11eb-96c0-009d2b88f05c.png)

**Comment by snowminc** [comment]
The requirements.txt reflects the Selenium version used to test the AJAX interaction within groupformer_list.
The WebDriver used for the Selenium test is geckodriver, a Firefox webdriver.
Tester must have Firefox installed and install the geckodriver executable and include its path on the system PATH to test.

To test the groupformer_list endpoint:
`python manage.py test min_iteration2.tests.SeleniumGroupformerList`
