### ISSUE TITLE
As a front-end developer, I want to have an expandable list of project inputs so that I can display the projects and descriptions for the instructor to input

### ISSUE THREAD

**Issue by KristianMischke** [snowminc/Groupformer#31]
Related to #5 

"+" button to add new projects
two text inputs: one for project name, one for project description

**Comment by snowminc** [comment]
#43 
Completed the setup for Project models to set up for the templating webpage on the front-end, for database interaction.

**Comment by snowminc** [comment]
Tests written found in:
app/groupformer/project_input_test/tests.py
