### ISSUE TITLE
As a backend dev, I want to have a database table for project attributes so that we can store that information

### ISSUE THREAD

**Issue by KristianMischke** [snowminc/Groupformer#33]
Related to #9 

database relations between the "form" and the attributes/questions

**Comment by Brunswick-Khorasan** [comment]
Related to #24 as well

**Comment by Brunswick-Khorasan** [comment]
Document with E-R diagram

[iss 24 33.pdf](https://github.com/snowminc/Groupformer/files/6222541/iss.24.33.pdf)

**Comment by Brunswick-Khorasan** [comment]
Revised E-R Diagram
[iss 24 33 rev2.pdf](https://github.com/snowminc/Groupformer/files/6240280/iss.24.33.rev2.pdf)
