### ISSUE TITLE
As a participant, I want to be able to input what other participants I would like to work with.

### ISSUE THREAD

**Issue by snakhon1** [snowminc/Groupformer#7]
Participants will be able to select other participants for who they would like to work with from the roster.

**Comment by Brunswick-Khorasan** [comment]
Updated description from SRS:

Participants will be able to select other participants for who they would like to work with from the roster. 

There will be a text box with a drop down list of all participants in the same section for the participant to select from. The participant will be able to select more than one participant from the drop down list.
