### ISSUE TITLE
As a participant, I want to be able to log in and be validated that I am a participant of an instance of the tool.

### ISSUE THREAD

**Issue by snakhon1** [snowminc/Groupformer#8]
Participants won’t be able to log in unless they are a participant for an instance of a link.

**Comment by KristianMischke** [comment]
Backend side of things.

Need an endpoint for "login" / validating a participant belong to the group they are trying to submit a response for.

If the email does not belong to the groupformer, should redirect to a "Permission" denied view.

If the email is in the groupformer, then redirect to the "Response Screen"

You don't need to worry about any popups or frontend stuff. Just a form-like endpoint that receives an email address (and a groupformer id)... maybe for until we decide on a URL structure you could do something like `/response_screen/{{group_former_id}}/login?email="jules@jules.jules"`
